name: zadanie 2
on:
  push:
    branches: [main, 'feature/**']
    paths-ignore: ['docs/**']
  pull_request:
    branches: [main]
env:
  GREETING: "Czesc z Actions"
jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Uzyj sekretu
        env:
          TOKEN: ${{ secrets.API_TOKEN }}
        run: echo "Dlugosc tokenu ${#TOKEN}"